apiVersion: cilium.io/v2alpha1
kind: CiliumSRv6VRF
metadata: # kpt-merge: /vrf1
  name: vrf1
  annotations:
    internal.kpt.dev/upstream-identifier: 'cilium.io|CiliumSRv6VRF|default|vrf1'
spec:
  vrfID: 2
  importRouteTarget: "65000:1"
  exportRouteTarget: "65000:1"
  rules:
  - selectors:
    - podSelector:
        matchLabels:
          vrf: vrf1
    destinationCIDRs:
    - 10.3.0.0/24
